services:
  test-db:
    image: postgres:16
    container_name: test-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  test-migrations:
    image: flyway/flyway:11.3
    container_name: test-migrations
    environment:
      - FLYWAY_URL=jdbc:postgresql://test-db:5432/postgres
      - FLYWAY_USER=postgres
    volumes:
      - ./src/main/resources:/flyway/sql
    depends_on:
      - test-db
    command: "migrate"
